### ISSUE TITLE
Missing Policy documets

### ISSUE THREAD

**Issue by niusealeo** [ipnz/Docs#2]
Some policies are missing:
- Digital Economy & Innovation
- Arts & Culture
- Christchurch Rebuild
- Criminal Justice
- Dolphins
- Cannabis

They can all be found at:
forum.internet.org.nz/?page_id=30

**Comment by dvkwong** [comment]
Done. BTW I used http://word-to-markdown.herokuapp.com/ to convert the word docx to markdown format, I then did a search and replace to get rid of some weird characters.
