### ISSUE TITLE
Newer Constitution already exists?

### ISSUE THREAD

**Issue by niusealeo** [ipnz/Docs#4]
Hi David, a version of the IP Constitution and Rules exists on the elections.org.nz website, here:

http://www.elections.org.nz/sites/default/files/bulk-upload/documents/internet_party_constitution_and_rules_13_may_14.pdf

Some of the main differences is that it doesn't include any reference to a "Party Visionary", and that a new Clause has been added to grant exec with powers to create by-laws.

The file name indicates it was created on 13th May 2014 - which indicates it might be an older version? However I thought it was the most recently amended version for 2015? Something that needs to be clarified with FL.

**Comment by dvkwong** [comment]
I copied the constitution from here the last update in December https://web.archive.org/web/20140215000000*/http://internet.org.nz

**Comment by niusealeo** [comment]
Cool thanks for everything David, just to confirm, I communicated with the
other members and they said the one on the elections website is the most
recent version.

**Comment by dvkwong** [comment]
Rules are now updated https://github.com/ipnz/Docs/blob/master/ConstitutionAndRules.md
